### ISSUE TITLE
Tabella della classifica attuale F1

### ISSUE THREAD

**Issue by Teodoro777** [Teodoro777/html#1]
Realizzare, usando l'html, una tabella rappresentante la classifica attuale dei piloti di formula 1

**Comment by Teodoro777** [comment]
Come faccio ad aumentare lo spazio tra le celle?

**Comment by FabioZTessitore** [comment]
in questa fase non ci interessa. E' compito del foglio di stile pensare alle apparenze

**Comment by FabioZTessitore** [comment]
non hai chiuso l'ultima riga
quando metti i caratteri speciali non dimenticare il ;
aggiungi una caption

**Comment by Teodoro777** [comment]
Fatto

**Comment by FabioZTessitore** [comment]
riga 94, manca ;
cmq ok
