### ISSUE TITLE
labels

### ISSUE THREAD

**Issue by FabioZTessitore** [Teodoro777/html#3]
guarda il file e vedi se ok

**Comment by Teodoro777** [comment]
Okk

**Comment by FabioZTessitore** [comment]
checkbox

**Comment by Teodoro777** [comment]
Prof ora ho aperto la pagina nel browser, non ho trovato differenza tra le la prima forma senza label e le altre 2..

**Comment by FabioZTessitore** [comment]
Si. Non sono elementi grafici ma servono a dare significato a quello che
scrivi (e poi saranno utili quando dovrai programmare)

Il martedì 8 novembre 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
le checkbox le hai capite?

**Comment by Teodoro777** [comment]
Si si c'è poco da capire ahah

**Comment by FabioZTessitore** [comment]
radio

**Comment by Teodoro777** [comment]
Okk

**Comment by FabioZTessitore** [comment]
campi nascosti

**Comment by FabioZTessitore** [comment]
ho aggiunto anche buttons, dammi conferma per entrambi

**Comment by Teodoro777** [comment]
Ho visto, ma i campi nascosti dove sono?? Cioè a che servono visto che non si vedono?

**Comment by FabioZTessitore** [comment]
A passare informazioni tra una chiamata e l'altra. Cmq non è importante per
ora. L'importante è che sai che ci sono e come si fanno

Il giovedì 10 novembre 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Ok allora va bene

**Comment by FabioZTessitore** [comment]
ho aggiunto textarea e select

**Comment by Teodoro777** [comment]
Okk

**Comment by FabioZTessitore** [comment]
http://htmldog.com/guides/html/

devi leggerti questi tutorial (tutti e tre)

**Comment by Teodoro777** [comment]
Ci metterò dei giorni... nel frattempo facciamo anche altro?

**Comment by FabioZTessitore** [comment]
non dire sciocchezze, ogni unità sono quattro parole
poi queste cose ti servono per fare il lavoro del sito

**Comment by Teodoro777** [comment]
Ok vedo di accellerare i tempi

2016-11-11 10:53 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
ok

**Comment by Teodoro777** [comment]
Prof sto alle ultime guide, mi potete dare qualche compito?

**Comment by FabioZTessitore** [comment]
Quando hai finito con le guide ci sono dei filmati

Come compiti potresti fare le pagine per gli eventi

Il martedì 22 novembre 2016, Teodoro <notifications@github.com> ha scritto:

**Comment by Teodoro777** [comment]
Ok potete già inviarmi i filmati
